// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetAJokeResponse, GetAJokeError } from './types.gen';

export const client = createClient(createConfig());

// New client configuration
const newClientConfig = createConfig({
  baseUrl: 'https://icanhazdadjoke.com',
  headers: {
    'Accept': 'application/json'
  }
});

// New client
export const newClient = createClient(newClientConfig);


export class DadJokeService {

  public static getAJoke<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
    return newClient.get<GetAJokeResponse, GetAJokeError, ThrowOnError>({
      ...options,
      url: '/'
    });
  }
  
}
